version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: whysosplash/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
  frontend:
    image: whysosplash/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: whysosplash/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80